<div class="content_part">
<div class="std"><p>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script src="http://www.galleri-artexpo.dk/skin/frontend/default/gallery_art/js/carouFredSel-6.1.0-packed.js" language="javascript" type="text/javascript"></script>
<script language="javascript" type="text/javascript">
			var $nc1 = $.noConflict();
			$nc1(function() {
				//	Variable number of visible items with variable sizes
				$nc1('#foo3').carouFredSel({
					width: 719,
					height: 125,
					prev: '#prev3',
					next: '#next3',
					auto: false
				});
			});
	</script></p>
	
<div class="row1">
	<?php $collection = Mage::getModel('custom/custom')->getCollection();
			foreach($collection as $coll):	?>
	<a href="<?php echo $coll->getLink() ?>">
   <div class="col1">
	<img alt="" src="<?php echo Mage::getBaseUrl('media').'blockimage/'.$coll->getFilename(); ?>">
	<div class="detail">
	<h2><?php $coll->getTitle() ?></h2>
	<?php echo $coll->getContent(); ?>
	</div>
	<div class="more"><img alt="" src="http://www.galleri-artexpo.dk/skin/frontend/default/gallery_art/images/arrow_white.png"></div>
	</div>
	</a>    
<?php endforeach ; ?>
</div>



